### ISSUE TITLE
Exception caught by services library

### ISSUE THREAD

**Issue by lublak** [Bungeefan/flutter_debug_overlay#1]
If i try to press Alt+F12

════════ Exception caught by services library ══════════════════════════════════
Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key event being sent doesn't properly set its modifier flags. This was the event: RawKeyDownEvent#59687(logicalKey: LogicalKeyboardKey#d0ba2(keyId: "0x200000100", keyLabel: "Control Left", debugName: "Control Left"), physicalKey: PhysicalKeyboardKey#ea6e1(usbHidUsage: "0x000700e0", debugName: "Control Left"), repeat: false) and its data: RawKeyEventDataWindows#8e01a(keyCode: 162, scanCode: 29, characterCodePoint: 0, modifiers: 0)
'package:flutter/src/services/raw_keyboard.dart':
raw_keyboard.dart:1
Failed assertion: line 695 pos 7: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty'

════════════════════════════════════════════════════════════════════════════════

**Comment by Bungeefan** [comment]
Hi, did the overlay open nonetheless?
And in which version did you test it?

**Comment by lublak** [comment]
@Bungeefan 
```
flutter_debug_overlay: ^0.1.4
Flutter 3.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 796c8ef792 (7 weeks ago) • 2023-06-13 15:51:02 -0700
Engine • revision 45f6e00911
Tools • Dart 3.0.5 • DevTools 2.23.1
```

Currently it just works without error. So i can not reproduce it. :/ So i think it can be closed

**Comment by Bungeefan** [comment]
Oh ok, just in case it happens again, here for documentation:
This seems to be a flutter related issue and has nothing to do with the code in this library, this was even already fixed in the main branch, just not yet released in stable:
https://github.com/flutter/flutter/issues/125672

**Comment by lublak** [comment]
@Bungeefan ahhh! :) thanks for the information.
In any case, it is very useful! <3
Maybe another option would be practical, if no debugEntries exist, that no debug tab is displayed. But that is quite irrelevant. It works and that is the main thing.

**Comment by Bungeefan** [comment]
Thank you for the nice feedback!
This was mainly to avoid having no tabs at all when disabling the others, but I will probably implement it so that it will be hidden. Thanks!
