### ISSUE TITLE
Incompatible with latest package_info_plus

### ISSUE THREAD

**Issue by hakonber** [Bungeefan/flutter_debug_overlay#5]
The latest version of package_info_plus is v8.0.0, which is not compatible with flutter_debug_overlay due to the upper bound in [pubspec.yaml](https://github.com/Bungeefan/flutter_debug_overlay/blob/60ee1a3529ef27c8be8f9369509e8f4ef5f94aa7/pubspec.yaml#L15):
```yml
package_info_plus: '>=4.0.2 <6.0.0'
```

**Comment by hakonber** [comment]
I've taken the liberty of creating a PR for this: https://github.com/Bungeefan/flutter_debug_overlay/pull/4

**Comment by Bungeefan** [comment]
Thanks for the notice and PR, merged!

**Comment by Bungeefan** [comment]
flutter_debug_overlay [0.1.7](https://pub.dev/packages/flutter_debug_overlay/versions/0.1.7) has been uploaded to pub.dev!
